import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider,SignIn,SignInButton,SignUpButton,SignedIn,SignedOut,UserButton } from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider signInForceRedirectUrl={'/chat'} afterSignOutUrl={'/'}>
        <html lang="en">
          
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="landing-container">
        <div className="floating-elements">
        <div className="floating-element"></div>
        <div className="floating-element"></div>
        <div className="floating-element"></div>
        <div className="floating-element"></div>
      </div>
      <header className="landing-header">
        <h1 className="logo">ReMail</h1>
        <div className="auth-buttons">
          <SignedIn>
         <UserButton/>
          </SignedIn>
          <SignedOut>
          <SignInButton  className="sign-in-btn">
            Sign In
          </SignInButton>
          <SignUpButton  className="sign-up-btn">
            Sign Up Free
          </SignUpButton>
          </SignedOut>
        </div>
      </header>
       {children}
       </div>        
       </body>
        </html>
      </ClerkProvider>
  );
}
